name: katas
version: 0.1.0.0
author: Attila Domokos <adomokos@gmail.com>
maintainer: adomokos@gmail.com
copyright: 2018 Attila Domokos
category: Console App
homepage: https://github.com/adomokos/hashmir#readme

# ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src/

executables:
  katas-exe:
    source-dirs: app/
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

tests:
  katas-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - containers
    other-modules:
      Katas.Lists.ExtractingSpec
      Katas.Lists.ComprehensionsSpec
      Katas.Lists.RangesSpec
      Katas.Lists.TuplesSpec
      Katas.Types.IntroSpec
      Katas.Types.MakingTypesSpec
      Katas.Types.RecordSpec
      Katas.Types.TypeParametersSpec
      Katas.Types.DerivedInstancesSpec
      Katas.Types.MoreDerivedInstancesSpec
      Katas.Flow.PatternMatchingSpec
      Katas.Flow.GuardsSpec
      Katas.Flow.WhereSpec
      Katas.Flow.LetItBeSpec
      Katas.Flow.CaseExpressionSpec
      Katas.Flow.RecursionsSpec
      Katas.Hofs.IntroSpec
      Katas.Hofs.LambdasSpec
      Katas.Hofs.FoldsSpec
      Katas.Hofs.ScansSpec
      Katas.Hofs.FunctionApplicationSpec
      Katas.Hofs.FunctionCompositionSpec
      Katas.Modules.IntroSpec
      Katas.Modules.ListFunctionsSpec
      Katas.Modules.CharFunctionsSpec
      Katas.Modules.MapFunctionalitySpec
      Katas.Modules.MapFunctionsSpec
      Katas.Modules.SetFunctionsSpec
